/*
===============================================================================
1. Exploratory Data Analysis & Core Business Measures
===============================================================================
Script Purpose:
    This script breaks down key database dimensions (Geography, Gender, Categories)
    and computes baseline aggregations to discover distributions and initial 
    revenue benchmarks.
===============================================================================
*/

-- --- Baseline Customer & Product Distributions ---

-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold_dta_dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold_dta_dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold_dta_dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average cost in each category?
SELECT
    category,
    ROUND(AVG(cost), 2) AS avg_cost
FROM gold_dta_dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- --- Financial Profile Baseline ---

-- What is the total revenue generated for each category?
SELECT 
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold_dta_fact_sales f
LEFT JOIN gold_dta_dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category 
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer?
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold_dta_fact_sales f
LEFT JOIN gold_dta_dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of items sold by countries?
SELECT 
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold_dta_fact_sales f
LEFT JOIN gold_dta_dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.country
ORDER BY total_sold_items DESC;
